version: '2.4'
services:
  app:
    build: .
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - redis
    networks:
      - isolated
      - exposed
  redis:
    image: redis:7.0.3-alpine
    restart: always
    networks:
      - isolated
networks:
  isolated:
    internal: true
  exposed: {}
